# Generated by Django 3.2.8 on 2021-10-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.IntegerField()),
                ('campo2', models.IntegerField()),
                ('campo3', models.IntegerField()),
            ],
        ),
    ]
