# Generated by Django 3.2.8 on 2021-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
